### ISSUE TITLE
[Suggestion] Standardize IDs to avoid the updates killing the existing Chroma maps

### ISSUE THREAD

**Issue by Fatalution** [Aeroluna/Chroma#10]
Basically, the title.

Ideally, prop id's should be standardized for Chroma. This would avoid the need to majorly redo the mod after the update that would change the environment(s) and their prop ids. As well as would revive all the maps that have their lighting broken thanks to updates

**Comment by Fatalution** [comment]
Well, I was talking about light IDs in the first comment on this suggestion. However, those all, IMO, should be in some way standardized to avoid future hassles

**Comment by Fatalution** [comment]
The way to do that, from what I could gather, would be to use a translation layer:

1. Chroma should use its own light and prop IDs
2. The prop and light IDs from the game should be translated to Chroma IDs using a translation table
3. Every time the Chroma map is being played - the Chroma should translate the IDs back to the game's IDs
4. Every time the update drops the translation table should be updated according to the new ID names

This allows for almost perfect backward and forward compatibility

**Comment by Aeroluna** [comment]
Implemented https://github.com/Aeroluna/Chroma/commit/a8fc978b282af145c6ed263bfcce3485a31bb039
