### ISSUE TITLE
360 Degree Map Bug

### ISSUE THREAD

**Issue by RobSkop** [Aeroluna/Chroma#15]
If I use the newest pre-release version of Chroma, all 360 Degree Maps aren't working anymore. I can't press the Play button.
Chroma Version v2.4.1 is not working, however v2.4.0 is working fine! All other mods are up to date and the newest Noodle Extensions is installed too.

**Comment by Aeroluna** [comment]
Fixed in source https://github.com/Aeroluna/Chroma/commit/fbbaf4df3d529beb703954d8a9eb60ed5b7ed344 
Release coming soon
