### ISSUE TITLE
Build instruction

### ISSUE THREAD

**Issue by cnlohr** [Aeroluna/Chroma#25]
I would love to be able to test this, but I can't figure out how to get my visual studio set up.  Are there build instructions anywhere, it looks like this thing octopuses around all over the place.

I got as far as to figure out where to put noodle, but I can't figure out how to get/put style cop where it needs to go or resolve any of the missing mod references.

(Check out noodle to the same folder as this.)

Edit: Use mod assistant to install the base layout of mods, make sure to get stuff like `SiraUtil` `CustomJSONData`, etc.  As you find missing references, see if you can use the mod assistant to install the reference.

```
git clone https://github.com/Aeroluna/Chroma --recurse-submodules
git clone https://github.com/Aeroluna/Heck--recurse-submodules
git clone https://github.com/Aeroluna/NoodleExtensions --recurse-submodules
```

**Comment by cnlohr** [comment]
Ok, seems installing this and installing it to visual studio does not help: https://marketplace.visualstudio.com/items?itemName=ChrisDahlberg.StyleCop

This has no clear mechanism to get the build working from what's missing: https://github.com/DotNetAnalyzers/StyleCopAnalyzers

I tried running nuget get the packages working `nuget restore Chroma.sln` to no avail, nor installing the BeatSaberModdingTools.Tasks package from nuget got me any further.

Would you consider for future projects being less reliant on tools not able to be installed by a series of git clones?

**Comment by JonnyXDA** [comment]
Just remove the reference to stylecop. I've pointed this out before but the author dismissed it as they still had the files locally so didn't see an issue.

Reference https://github.com/Aeroluna/NoodleExtensions/pull/46

**Comment by cnlohr** [comment]
🤯 well, that gets me past the stylecop issues.

**Comment by cnlohr** [comment]
Ok, further instructions:

* Create the csproj file, in the Chroma folder, create `Chroma.csproj.user` then place the following in it (considering where your beat saber install path is)

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <BeatSaberDir>C:/Program Files (x86)/Steam/steamapps/common/Beat Saber</BeatSaberDir>
  </PropertyGroup>
</Project>
```
Also paste this in as Noodle.csproj.user and Heck.csproj.user

**Comment by cnlohr** [comment]
You will need to build Heck, and you may need to build noodle first.  Building projects will place the output dll in the plugins folder specified by the .csproj.user file.

**Comment by cnlohr** [comment]
Next step, after installing SiraUtil from mod manager, open and close beatsaber.  This will put the .dll in place.

**Comment by cnlohr** [comment]
You may need to rebuild some of the packages depending on errors you get.

**Comment by cnlohr** [comment]
Another note:  you may need the `dev` branch of noodleextensions

**Comment by DogBot100** [comment]
And just something to add on if building heck or chroma and it gives you a can’t find noodle extensions error you may need to download a new copy of noodle and build it

**Comment by Aeroluna** [comment]
Admittedly, the StyleCop references are a mess, however, build instructions will not be written.
