### ISSUE TITLE
Doesnt work.

### ISSUE THREAD

**Issue by scolastico** [Aeroluna/Chroma#26]
It does not show up in the mod assistant and if i install it manually (downloading last build from releases and copying dll into plugins folder) my maps arent working anymore they have only at the start 1 block and after that the map is empty... Tryd reinstalling game + mod assistant multiple times.

**Comment by scolastico** [comment]
To be sure i did nothing wrong ho did you guys installed the plugin?

**Comment by Akitakek** [comment]
It's not updated for 1.16.1 yet, have patience it'll be out soon-ish.
