### ISSUE TITLE
Chroma wont work at all

### ISSUE THREAD

**Issue by CharlieTheRobot1** [Aeroluna/Chroma#28]
I have chroma in the plugins folder and noodle extensions installed but it doesn't even show up in the game that its even working.
I have ran the IPA and everything it's just not working

**Comment by BdenandMe** [comment]
I am having the same problem. I might just wait until it comes out on mod assistant and maybe that will fix it.

**Comment by CharlieTheRobot1** [comment]
> I am having the same problem. I might just wait until it comes out on mod assistant and maybe that will fix it.

ok i will probably do the same lol

**Comment by MitchellShapiro** [comment]
I believe this mod and Noodle Extensions now requires the Heck mod as a dependency. [https://github.com/Aeroluna/Heck/releases/tag/v1.0.0](https://github.com/Aeroluna/Heck/releases/tag/v1.0.0)

**Comment by CharlieTheRobot1** [comment]
> I believe this mod and Noodle Extensions now requires the Heck mod as a dependency. https://github.com/Aeroluna/Heck/releases/tag/v1.0.0

so it works now but i cant click play on a song

**Comment by Aeroluna** [comment]
This is a repo for the source code, help will not be provided for installing the mod.
