### ISSUE TITLE
Chroma in plugins folder but not working in-game

### ISSUE THREAD

**Issue by PressAAlexYT** [Aeroluna/Chroma#31]
Hey. I just downloaded both noodle extensions and chroma and then put both in the plugins folder but when I load up the game they don't pop up or work (Still says missing requirement on maps). Is it to do with the patch notes saying added dependency to Heck? As if so i'm not 100% sure what that is

**Comment by PressAAlexYT** [comment]
Sorry if you already know about this issue

**Comment by maximalmax90** [comment]
You also need to install [https://github.com/Aeroluna/Heck](Heck)

**Comment by Aeroluna** [comment]
This is a repo for the source code, help will not be provided for installing the mod.
