### ISSUE TITLE
Environment Lights not Working as Intended

### ISSUE THREAD

**Issue by Sw1ftSN** [Aeroluna/Chroma#32]
Default Environment lights will be stuck to the colors of your sabers; like in the un-modded version of beat saber.

**Comment by Aeroluna** [comment]
what

**Comment by Fatalution** [comment]
I guess you have forgot to install Heck. It's a new dependency that should be installed manually (until the mod is approved on the ModAssistant). Without it, Chroma won't work and Chroma maps won't function as intended.

Also, 

> what

LUL

**Comment by Sw1ftSN** [comment]
> I guess you have forgotten to install Heck. It's a new dependency that should be installed manually (until the mod is approved on the ModAssistant). Without it, Chroma won't work and Chroma maps won't function as intended.
> 
> Also,
> 
> > what
> 
> LUL

No, Heck is installed. I play a lot of mod charts, and chroma + noodle extensions is a requirement for all of them. I installed the two mods, along with their dependency; heck. Chroma maps work. Walls, bombs, etc are all "chroma-ized." The only thing not working are the lights.

**Comment by Aeroluna** [comment]
Having Environment Effects/Expert+ Environment Effects on "No Flickering" or "No Effects" will not work with Chroma

![image](https://user-images.githubusercontent.com/40481393/120874967-0d8eeb80-c55e-11eb-9485-383e4a815467.png)

**Comment by Sw1ftSN** [comment]
> Having Environment Effects/Expert+ Environment Effects on "No Flickering" or "No Effects" will not work with Chroma
> 
> ![image](https://user-images.githubusercontent.com/40481393/120874967-0d8eeb80-c55e-11eb-9485-383e4a815467.png)

I believe I have this on. I'll check and get back to you, but I've turned this onto All Effects before.

**Comment by Sw1ftSN** [comment]
> Having Environment Effects/Expert+ Environment Effects on "No Flickering" or "No Effects" will not work with Chroma
> 
> ![image](https://user-images.githubusercontent.com/40481393/120874967-0d8eeb80-c55e-11eb-9485-383e4a815467.png)

After checking beatsaber, it does appear that I have both of these set to All Effects. Even after a restart, the background lighting refused to work. I appreicate any further help on this.

**Comment by Sw1ftSN** [comment]
> > Having Environment Effects/Expert+ Environment Effects on "No Flickering" or "No Effects" will not work with Chroma
> > ![image](https://user-images.githubusercontent.com/40481393/120874967-0d8eeb80-c55e-11eb-9485-383e4a815467.png)
> 
> After checking beatsaber, it does appear that I have both of these set to All Effects. Even after a restart, the background lighting refused to work. I appreicate any further help on this.

Upon further inspection, it seems as if this mod has compatibility issues with [Re Processor](https://github.com/headassbtw/ReProcessor/). However, I'm not too sure about this, since I reinstalled all my mods **except** that one, and it started working. I'll close the issue here, but I'd investigate this further if you feel the need to. However, this may have just been a bad install on my part. Thank you for your time.
