### ISSUE TITLE
Won't let me hit the blocks.

### ISSUE THREAD

**Issue by homebrewuser** [Aeroluna/Chroma#35]
*sighs* i've looked everywhere for answers to why (on Noodle Extension maps) when the notes/sabers change colour and a hit a note it says "Miss" My recorded that I use is broken but here is the logs for chroma:
[_latest.log](https://github.com/Aeroluna/Chroma/files/6633182/_latest.log)

but that might not help so here is a log of the game:
[_latest.log](https://github.com/Aeroluna/Chroma/files/6633188/_latest.log)

i hope you can help Aeroluna. But if you cant that's fine 

ok bye i must go and cry in a dark corner in my room

**Comment by Aeroluna** [comment]
Please update your Chroma to latest version (v2.4.7) and see if that helps

**Comment by homebrewuser** [comment]
v2.4.7... ok got it

**Comment by homebrewuser** [comment]
hold on i have that

**Comment by homebrewuser** [comment]
i have the latest version...

**Comment by Fatalution** [comment]
> hold on i have that

No, you don't. Your log shows 2.4.6

**Comment by homebrewuser** [comment]
:o

**Comment by homebrewuser** [comment]
oh no
should i go and check that now?

**Comment by homebrewuser** [comment]
![20210610195031_1](https://user-images.githubusercontent.com/72621433/121581260-8cd06380-ca25-11eb-8ef5-199997c9b910.jpg)
thanks!
(This is in a Noodle map)
