### ISSUE TITLE
Does not work on 1.16.2

### ISSUE THREAD

**Issue by JonteonGithub** [Aeroluna/Chroma#36]

**Comment by Fatalution** [comment]
Launch the game with Chroma. Try and Chroma map. Then, please provide the _latest.log, that is found in your Logs folder. 

We cannot help you without the log

**Comment by JonteonGithub** [comment]
@Fatalution , here is the log: 
https://pastebin.com/DfgAc2UZ

**Comment by Fatalution** [comment]
> @Fatalution , here is the log:
> https://pastebin.com/DfgAc2UZ

I have asked for the full _latest.log file, not the snippet :) 
However, as I can see, you are trying to launch a legacy Chroma map. Please provide the full _latest.log file (you can just drag and drop it here) as well as the link to the map

**Comment by JonteonGithub** [comment]
@Fatalution , I provided the full _latest.log file in the pastebin. Idk if it's not compatible with 1.16.2 yet or if it is something else.

**Comment by Fatalution** [comment]
> @Fatalution , I provided the full _latest.log file in the pastebin. Idk if it's not compatible with 1.16.2 yet or if it is something else.
The _latest.log file that we would need would be located in UserData/Logs folder. NOT Chroma folder. 

It would start with something like this: 
[DEBUG @ 20:57:57 | IPA/LibraryLoader] Resolving library 0Harmony, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null

Your log is just Chroma, which doesn't print the full picture

**Comment by JonteonGithub** [comment]
@Fatalution , I cannot play those maps without chroma and noodle extensions, and it is not finding it.

**Comment by JonteonGithub** [comment]
Well anyways, if you need the GAMES logs, here: 
https://pastebin.com/2g42V2bw

**Comment by Fatalution** [comment]
> @Fatalution , I cannot play those maps without chroma and noodle extensions, and it is not finding it.

You don't need to play the maps without Chroma and Noodle Extensions. What we need you to do, since you opened the issue, is:

1. Launch the map in question with Chroma, Heck and NE installed
2. Provide the full _latest.log found in UserData/Logs
3. Provide the link to the map

**Comment by Fatalution** [comment]
> Well anyways, if you need the GAMES logs, here:
> https://pastebin.com/2g42V2bw

I don't see Chroma installed here, at all

**Comment by JonteonGithub** [comment]
Oh, I found it. It's on the 1.16.1 plugins, I'm stupid
