### ISSUE TITLE
Unclear that Heck is a required dependency

### ISSUE THREAD

**Issue by vinyldarkscratch** [Aeroluna/Chroma#39]
It's unclear that Heck is now a required dependency for this plugin, as well as for NoodleExtensions.  This caused both myself and a friend of mine confusion for a long time, until I looked at the log and figured it from there.  I am requesting that a blurb should be added to the readme indicating the dependency plugins.

**Comment by cgjeffries** [comment]
While it should probably eventually be added to the readme, the new dependency to Heck is mentioned within the first 2 lines of the release notes on the release page that you download the zip from, so I wouldn't call it "unclear".

**Comment by lkkuma** [comment]
If there is a new dependency, then it should be stated on the ReadMe, preferably with a link to the proper source to download.
As someone who generally doesn't involve himself much in the community, I have never heard of "Heck" until looking to download Chroma.
This leads to a lot of chasing leads and research to figure out both what it is, and where the proper source to download it is.

The fact is that listing a new dependency in the release notes is not clear.
It is a very significant change that must also be updated as such in the main ReadMe.
If you have to go looking for something that's required and it's not stated anywhere except for the release notes, then it's simply not clear.

Please, when you have some time, update the ReadMe with this new dependency and where we can find it.
Thank you.

**Comment by Aeroluna** [comment]
Although the original intention was to upload to BeatMods and have that be the main method of installing the mod (which would handle dependencies), it has become clear that it will take a while to be approved (and has taken a while) and Github will remain the only place to download the mod until further notice. The release page has been updated to list the required dependencies.
