### ISSUE TITLE
Lightshow mode doesn't remove blocks on maps using NoodleExtensions

### ISSUE THREAD

**Issue by roothorick** [Aeroluna/Chroma#4]
I haven't drilled down 100% which maps are affected and which are not, but the pattern across all maps I've tested has been NE wallmaps (such as Unholy Crusade) will still have blocks, while on other maps, including wallmaps using MappingExtensions instead, the blocks are removed. In all cases, the sabers are disabled.

**Comment by Aeroluna** [comment]
Fixed in Chroma (https://github.com/Aeroluna/Chroma/commit/bb3797029a290d5b93578eef3e1c23b45032e0f1) and Noodle Extensions (https://github.com/Aeroluna/NoodleExtensions/commit/90c9ed688fef9fee204a14a84cd436399054441f).
