### ISSUE TITLE
When Chroma is installed, none of my custom songs will load their options/play menu

### ISSUE THREAD

**Issue by BurgerBoiOG** [Aeroluna/Chroma#42]
When Chroma is installed, none of my custom songs will load their options/play menu that would normally pop up to the left. It just sits there loading forever.

**Comment by BurgerBoiOG** [comment]
[2021.09.02.22.53.31.log](https://github.com/Aeroluna/Chroma/files/7103004/2021.09.02.22.53.31.log)
[2021.09.01.23.58.05.log.gz](https://github.com/Aeroluna/Chroma/files/7103005/2021.09.01.23.58.05.log.gz)

wasnt sure if you needed the winrar or txt so I gave you both

**Comment by Aeroluna** [comment]
CustomJSONData (2.0.4) is not currently updated for Beat Saber version 1.17.0, please be patient as the mods are updated.

**Comment by BurgerBoiOG** [comment]
Ohh i didnt even realize there was a new update for the game until just now. That makes sense. Lol take your time
