### ISSUE TITLE
Add option to remove block color enforcement

### ISSUE THREAD

**Issue by pkdan** [Aeroluna/Chroma#44]
If possible, please add the option to disable the block colors enforcement. Just like it is possible to play with static lights on a chroma map. It would be great to be able to use personal block colors on Chroma required maps since the play button is greyed out if I try to disable the mod. 

Sometimes the colors a mapper picks can be completely inverted or not differentiated enough for colorblind people. This can lead to some bad time if people are not able to play with the colors they learned. A button to disable the block colors without disabling Chroma would be nice.

**Comment by Fatalution** [comment]
> the play button is greyed out if I try to disable the mod. 

That means that the mapper has decided to put Chroma as a requirement, not as a suggestion. That's mapper's choice. You can disable Chroma on the maps where Chroma is a suggestion. 

If a mapper put Chroma as a requirement, it is:

1. Either the mapper wanted you to experience the map the way it is 
2. Either the mapper is not knowledgeable enough to know the difference between requirement and a suggestion

**Comment by pkdan** [comment]
Well yes. The second point is what could be useful when playing maps from people who are not entirely familiar with Chroma and the way it works. Some might not even realize they set custom block colors for everyone maybe. That is the issue I was hoping to fix.

Different block colors can be lead to a bad experience if the colors are inverted or too close to each other. Having an option to keep chroma on and only disable custom block colors would be very useful for colorblind people especially.

**Comment by Aeroluna** [comment]
As @Fatalution has said, it is up to the mapper's discretion whether a map requires changing note colors or not. This will not be changed.
