### ISSUE TITLE
Colors not enforcing properly

### ISSUE THREAD

**Issue by renycs** [Aeroluna/Chroma#49]
I made a NE / Chroma map, and noticed that different people are getting one of two sets of colors. 

The map colors are green / blue, but some people are getting red / black when playing it (that changes later when colors are animated). The map is setting the colors properly in the info.dat, and Override Default Colors is asked to be off by _heck.

Map ID:
https://beatsaver.com/maps/1ddab

Red/Black: https://www.twitch.tv/videos/1205408987?sr=a&t=19490s

The colors displayed for me (regardless if override default colors is on or not) are green/blue though:  https://drive.google.com/file/d/1aweDU69afGUnNmbXxBRhneHbrFfRCEa9/view?usp=sharing

**Comment by Fatalution** [comment]
Hello.

If your map uses custom colors defined in the diff file (i.e. not Chroma blocks/events, but redefined sets of 2 colors for blocks and events) - then you can't enforce it. The user can easily disable custom map colors in SongCore settings - and that's likely what happened.

If you want the colors to be enforced, use Chroma events.

**Comment by Aeroluna** [comment]
> The map is setting the colors properly in the info.dat
The color fields in the info.dat are SongCore fields, and as such are not handled by Chroma. As Fatalution stated, the user has disabled custom map colors within the SongCore settings.
