### ISSUE TITLE
Right Hand Phasing Through Blocks

### ISSUE THREAD

**Issue by CatSack** [Aeroluna/Chroma#9]
I know this sounds dumb, as Chroma is a lighting mod and shouldn't affect gameplay whatsoever but I keep having an issue where whenever I have Chroma lighting effects enabled on a chart (only some charts, only some of the time) my right hand phases through blocks without cutting them. It plays the block cut sound and shows me my score for the cut, but counts as a miss. As soon as I disable Chroma, it goes back to normal. I honestly have no idea what the issue is, help would be appreciated!

**Comment by Aeroluna** [comment]
Fixed in TrickSaber https://github.com/ToniMacaroni/TrickSaber/releases/tag/1.0.1 , update that mod. In the future, please attach a log file to help debugging
